---
- name: Задание 1.2 — Установка и настройка tuned
  hosts: all
  become: true
  tasks:
    - name: Установить пакет tuned
      ansible.builtin.package:
        name: tuned
        state: present

    - name: Запустить сервис tuned и добавить в автозагрузку
      ansible.builtin.systemd_service:
        name: tuned
        state: started
        enabled: true
