---
- name: Задание 1.1 — Скачивание и распаковка Apache Kafka
  hosts: all
  become: true
  tasks:
    - name: Скачать архив Apache Kafka (Надежное зеркало)
      ansible.builtin.get_url:
        url: "https://yandex.ru"
        dest: "/tmp/kafka_2.13-3.5.1.tgz"
        mode: '0644'
        force: true

    - name: Создать папку для распаковки
      ansible.builtin.file:
        path: "/opt/kafka"
        state: directory
        mode: '0755'

    - name: Распаковать архив на удаленном хосте
      ansible.builtin.unarchive:
        src: "/tmp/kafka_2.13-3.5.1.tgz"
        dest: "/opt/kafka"
        remote_src: true
