---
- name: Задание 2 — Динамический motd с характеристиками хоста
  hosts: all
  become: true
  vars:
    dynamic_motd: |
      =======================================================
      Приветствуем системного администратора! Желаем хорошего дня!
      Текущий хост: {{ ansible_facts['hostname'] }}
      IP-адрес:     {{ ansible_facts['default_ipv4']['address'] }}
      =======================================================
  tasks:
    - name: Применить динамический шаблон приветствия
      ansible.builtin.copy:
        content: "{{ dynamic_motd }}"
        dest: "/etc/motd"
        owner: root
        group: root
        mode: '0644'
