---
- name: Определить переменные для OS семейства Debian
  ansible.builtin.set_fact:
    apache_package: "apache2"
    apache_service: "apache2"
    web_dir: "/var/www/html"
  when: ansible_facts['os_family'] == "Debian"

- name: Определить переменные для OS семейства RedHat
  ansible.builtin.set_fact:
    apache_package: "httpd"
    apache_service: "httpd"
    web_dir: "/var/www/html"
  when: ansible_facts['os_family'] == "RedHat"

- name: Установить веб-сервер Apache
  ansible.builtin.package:
    name: "{{ apache_package }}"
    state: present

- name: Создать index.html на основе системных фактов
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ web_dir }}/index.html"
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache Service

- name: Открыть порт 80 в ufw (Debian/Ubuntu)
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ansible_facts['os_family'] == "Debian"
  ignore_errors: true

- name: Открыть порт 80 в firewalld (RedHat/CentOS)
  ansible.posix.firewalld:
    port: 80/tcp
    permanent: true
    state: enabled
    immediate: true
  when: ansible_facts['os_family'] == "RedHat"
  ignore_errors: true

- name: Обеспечить запуск Apache и добавить в автозагрузку
  ansible.builtin.systemd_service:
    name: "{{ apache_service }}"
    state: started
    enabled: true

- name: Проверить доступность веб-страницы (Ожидаем HTTP 200)
  ansible.builtin.uri:
    url: "http://localhost/index.html"
    status_code: 200
  register: http_check_result

- name: Отобразить статус проверки
  ansible.builtin.debug:
    msg: "Проверка успешна! Код ответа веб-сервера: {{ http_check_result.status }}"
